### Задание 1

In [13]:
import numpy as np
# а)

A = np.array([[1, -2], [3, -4]])
B = np.array([1, 7])
res = np.linalg.solve(A, B)

n = 1
for el in res:
    print(f'x{n} = {round(el)}')
    n += 1

x1 = 5
x2 = 2


In [14]:
# б)

A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
B = np.array([10, -2, 1])
res = np.linalg.solve(A, B)

n = 1
for el in res:
    print(f'x{n} = {round(el)}')
    n += 1

x1 = 2
x2 = -1
x3 = 1


### Задание 2

In [22]:
import scipy.linalg

A = np.array([[1, 2, 4],
              [2, 9, 12],
              [3, 26, 30]]
             )
P, L, U = scipy.linalg.lu(A)

print(f'L: \n{L}')

L: 
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


In [23]:
A = np.array([[1, 1, 2, 4],
              [2, 5, 8, 9],
              [4, 22, 53, 33]]
             )
P, L, U = scipy.linalg.lu(A)

print(f'L: \n{L}')

L: 
[[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.25 0.75 1.  ]]


### Задание 3

In [21]:
A = np.array([[2, 1, 3],
              [11, 7, 5],
              [9, 8, 4]]
             )
P, L, U = scipy.linalg.lu(A)

print(f'P: \n{P}')
print(f'L: \n{L}')
print(f'U: \n{U}')

print(np.dot(P, A) - np.dot(L, U))

print(f'A = L * U: \n{np.dot(L, U)}')

B = np.array([1, -6, -5])
res = np.linalg.solve(A, B)

n = 1
for el in res:
    print(f'x{n} = {round(el)}')
    n += 1

P: 
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L: 
[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
U: 
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]
[[-2.  1. -1.]
 [-7. -7. -1.]
 [ 9.  6.  2.]]
A = L * U: 
[[11.  7.  5.]
 [ 9.  8.  4.]
 [ 2.  1.  3.]]
x1 = -1
x2 = 0
x3 = 1
