### Задание 1

In [2]:
import numpy as np
A = np.array([[-1, -6],
              [2, 6]])
w, v = np.linalg.eig(A)

n = 1
for el in w:
    print(f'λ{n} = {el}')
    n += 1
    
print(f'Собственные векторы:\n{v}')

λ1 = 2.0
λ2 = 3.0
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


### Задание 2

In [3]:
A = np.array([[-1, 0],
              [0, -1]])
w, v = np.linalg.eig(A)
n = 1
for el in w:
    print(f'λ{n} = {el}')
    n += 1

λ1 = -1.0
λ2 = -1.0


$$Получаем, что\ λ_1 = λ_2 = -1$$
$$Поворот\ на\ 180\ градусов\ меняет\ знак\ у\ координат\ на\ противоположный\ (e_1, e_2)\ -> (-e_1, -e_2)$$
$$=> λ\ должна\ быть\ равна\ -1 => любой\ вектор\ является\ для\ данного\ оператора\ поворота\ будет\ собственным$$

### Задание 3

In [4]:
A = np.array([[1, 1],
              [-1, 3]])
B = np.array([1, 1])
np.dot(A, B)

array([2, 2])

$$2 * (1, 1) = (2, 2)$$
$$=> Вектор\ x = (1, 1)\ является\ собственным\ вектором\ линейного\ оператора, заданного\ матрицей\ A$$

### Задание 4

In [5]:
A = np.array([[0, 3, 0],
              [3, 0, 0],
              [0, 0, 3]])
B = np.array([3, -3, -4])
np.dot(A, B)

array([ -9,   9, -12])

$$Получаем\ (-3, -3, 3), что\ не\ является\ λ$$ 
$$=> Вектор\ x = (3, -3, -4)\ не\ является\ собственным\ вектором\ линейного\ оператора, заданного\ матрицей\ A$$