### Задание 1

In [1]:
import numpy as np

A = np.matrix([[1, 2, 0],
               [0, 0, 5],
               [3, -4, 2],
               [1, 6, 5],
               [0, 1, 0]
              ])

U, s, W = np.linalg.svd(A)
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'Матрица D:\n{np.round(D, 2)}')
print(f'Матрица U:\n{np.round(U, 2)}')
print(f'Матрица V:\n{np.round(V, 2)}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [9]:
# Проверка:
print(np.around(np.dot(np.dot(U, D), V.T)))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


### Задание 2

In [3]:
# а) норма Фробениуса
round(np.linalg.norm(A), 3)

11.045

In [2]:
# б) евклидова норма
round(max(s), 3)

8.825