### Задание 1

а) Не перемножаются (2 и 4) <br>
б) 2 х 3 <br>
в) 8 х 8 <br>
г) 4 х 4

### Задание 2

In [9]:
import numpy as np

A = np.array([[1, -2],
              [3, 0],
             ])
B = np.array([[4, -1],
              [0, 5],
             ])
print(A + B)

[[ 5 -3]
 [ 3  5]]


In [11]:
print(np.dot(A, B))

[[  4 -11]
 [ 12  -3]]


In [14]:
print(np.dot(B, A))

[[ 1 -8]
 [15  0]]


### Задание 3

In [5]:
A = np.array([[1, 7],
              [3, -6],
             ])
B = np.array([[0, 5],
              [2, -1],
             ])
C = np.array([[2, -4],
              [1, 1],
             ])
print(3 * A - 2 * B + 4 * C)

array([[ 11,  -5],
       [  9, -12]])

### Задание 4

In [18]:
A = np.matrix([[4, 1],
              [5, -2],
              [2, 3]
             ])
A_T = A.T

print(f'Транспонированная матрица:\n {A.T}')
print(f'A * AT:\n {A * A_T}')
print(f'AT * A:\n {A_T * A}')

Транспонированная матрица:
 [[ 4  5  2]
 [ 1 -2  3]]
A * AT:
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
AT * A:
 [[45  0]
 [ 0 14]]
